version: 0.2

phases:
    install:
        runtime-versions:
            php: 8.4
            nodejs: 24
        commands:
            - echo [buildspec] Entered the install phase...
            - composer install --prefer-dist --no-interaction --no-progress
            - npm ci

    pre_build:
        commands:
            - echo [buildspec] Entered the pre_build phase...
            - cp .env.example .env
            - php artisan key:generate --force

    build:
        commands:
            - echo [buildspec] Entered the build phase...
            - echo [buildspec] Build started on `date`
            - npm run build
            - php artisan test

    post_build:
        commands:
            - echo [buildspec] Entered the post_build phase...
            - echo [buildspec] Build completed on `date`
            - composer install --no-dev --prefer-dist --no-interaction --no-progress --optimize-autoloader
            - php artisan optimize:clear
            - rm -f .env
            - rm -rf node_modules

artifacts:
    files:
        - '**/*'
    discard-paths: no
